spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true  # Changed to true for type mapping
        spring.json.type.mapping: accountEvent:com.example.account.event.AccountEvent

  mail:
    host: mail-dev
    port: 1025
    properties:
      mail:
        smtp:
          starttls:
            enable: false
          auth: false

server:
  port: 10080

application:
  config:
    auth-url: http://localhost:8222/api/v1/auth
    kafka:
      transaction-topic: transaction-events  # Custom topic name configuration
      retry-interval-ms: 1000