server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: account-service
          uri: lb:http://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**
        - id: transaction-service
          uri: lb:http://TRANSACTION-SERVICE
          predicates:
            - Path=/api/v1/transactions/**
        - id: loan-service
          uri: lb:http://LOAN-SERVICE
          predicates:
            - Path=/api/v1/loans/**
management:
  tracing:
    sampling:
      probability: 1.0

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/micro-services

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
