spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/loan
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 10060
# Microservice URLs
application:
  config:
    account-url: http://gateway:8222/api/v1/accounts
    auth-url: http://gateway:8222/api/v1/customers
